require("dotenv").config();
const retrievalQueue = require("../queue/redisQueue");

// fake metadata retrieval to simulate a semantic platform
async function fetchMetadata(itemId) {
  await new Promise(resolve => setTimeout(resolve, 1000));

  return {
    itemId,
    title: `Metadata for ${itemId}`,
    summary: "Synthetic metadata generated by the Fleet-style demo worker.",
    tags: ["semantic", "fleet-style", "demo"]
  };
}

retrievalQueue.process(async job => {
  const { itemId } = job.data;
  const metadata = await fetchMetadata(itemId);
  return { status: "completed", metadata };
});

console.log("Retrieval worker listening for jobs…");
